### ISSUE TITLE
About function is_consteval

### ISSUE THREAD

**Issue by cxcIvan** [microsoft/proxy#105]
```
template <class Expr>
consteval bool is_consteval(Expr)
    { return requires { typename std::bool_constant<(Expr{}(), false)>; }; }
```
Hello author, I am learning about your project. I noticed that your function is used to determine whether Expr can be called. It uses typename to determine whether the template generated by std::bool_constant is a type for calling. So I think if this function is changed to the following, it should also meet your needs.

```
template <class Expr>
consteval bool is_consteval(Expr)
    { return requires { Expr{}(); }; }
```
What are your considerations for adopting the current method? Is it to facilitate further expansion of the code in the future?
Looking forward to your reply

**Comment by mingxwa** [comment]
@cxcIvan `is_consteval()` is not intended to "determine whether `Expr` can be called" (in this case, `std::is_invocable_v<Expr>` is good enough), but to "determine whether the body of `Expr` can be evaluated at compile-time". This is required in many places in the implementation of `proxy`.

For example, for a given facade type `F`, `F::constraints` shall be a compile-time constant, rather than a runtime value. We can use `is_consteval([] { return F::constraints; })` ([link](https://github.com/microsoft/proxy/blob/d75d1fd87228cbdca68f6218e8be3f5603e94db9/proxy.h#L379C17-L379C59)) to inspect at compile-time. If `F::constraints` is a runtime value (we have a [unit test](https://github.com/microsoft/proxy/blob/d75d1fd87228cbdca68f6218e8be3f5603e94db9/tests/proxy_traits_tests.cpp#L274-L285) case for this scenario, where `constraints` is not `constexpr` but `static inline`), `facade<F>` will be evaluated to `false`.

Note that `is_consteval()` is a part of implementation details of `proxy`, not publically documented, and may change in the future. Please avoid depending on anything in `namespace details`, or your code may break in a future update. Looking forward your further feedback!

**Comment by frederick-vs-ja** [comment]
`requires { typename std::bool_constant<(Expr{}(), false)>; }` detects whether `Expr{}()` is a well-formed core constant expression, while `requires { Expr{}(); }` only detects whether `Expr{}()` is well-formed (in the immediate context). We definitely want the former (or even stronger one).

I wonder whether the current require-expression is strong enough... E.g. in this case
https://github.com/microsoft/proxy/blob/d75d1fd87228cbdca68f6218e8be3f5603e94db9/proxy.h#L379-L382

it seems that `is_consteval([] { return F::constraints; })` can be `true` even if `F::constraints` is a `static constexpr int` member, and hence a hard error can be produced instead of `false`.

**Comment by mingxwa** [comment]
@frederick-vs-ja Thank you for the explanation. In the definition of `facade_traits`, existence and type of `F::constraints` will be checked before calling `is_facade_constraints_well_formed<F>()` in the `required` clause. This will reject a `static constexpr int` without producing a hard error.

https://github.com/microsoft/proxy/blob/d75d1fd87228cbdca68f6218e8be3f5603e94db9/proxy.h#L428-L439

**Comment by frederick-vs-ja** [comment]
> In the definition of `facade_traits`, existence and type of `F::constraints` will be checked before calling `is_facade_constraints_well_formed<F>()` in the `required` clause. This will reject a `static constexpr int` without producing a hard error.

Hmm, thanks for confirming this! Would it be better to move `{ F::constraints } -> std::same_as<const proxiable_ptr_constraints&>;` into `is_facade_constraints_well_formed`?

**Comment by mingxwa** [comment]
@frederick-vs-ja I agree. Moving `{ F::constraints } -> std::same_as<const proxiable_ptr_constraints&>` into `is_facade_constraints_well_formed()` does make the code clearer.

**Comment by cxcIvan** [comment]
ok，thank you for this answer. I understand it.
