### ISSUE TITLE
Provide c++20 module interface

### ISSUE THREAD

**Issue by alvarogalloc** [microsoft/proxy#126]
I think it would be better to take a step forwards into modern c++ for the ones that are including modules in their projects. It would save the time to make the bridge themselves

**Comment by mingxwa** [comment]
@alvarogalloc Thank you for the feedback! We have tried this since proxy 1.0 (#33), but eventually decided to introduce a number of macros since 2.0 to improve usability. Since modules are not friendly with macros, we have removed the task from our short-term planning.

The only reason we keep the macros in `proxy` is that the existing C++ template system does not support generating functions with different names. On the other hand, we are working closely with other experts in the C++ committee to build better compile-time reflection facilities for code generation. However, this work may take years (at least not feasible for C++26).
