### ISSUE TITLE
Can pro::facade_builder work with template?

### ISSUE THREAD

**Issue by cxxamz** [microsoft/proxy#165]
```C++
#include <span>
#include <proxy/proxy.h> // __msft_lib_proxy 202408L

PRO_DEF_MEM_DISPATCH(get_size, size);
PRO_DEF_MEM_DISPATCH(get_data, data);

template<typename T = std::byte> 
using Memory = pro::facade_builder
    ::add_convention<get_size, std::size_t() const noexcept>
    ::add_convention<get_data, std::span<T const>() const noexcept>
    ::add_convention<get_data, std::span<T>() noexcept>
    ::support_copy<pro::constraint_level::none>
::build;
```

![image](https://github.com/user-attachments/assets/b5632950-8c8b-48c3-9d6a-dd0dc4432ff9)

**Comment by mingxwa** [comment]
It is because `add_convention<get_data, std::span<T const>() const noexcept>` depends on a template parameter `T`. As per C++ template syntax, a subsequent type deduction (i.e., `add_convention<get_data, std::span<T>() noexcept>`) needs to be prefixed with the `template` keyword.

```cpp
template<typename T = std::byte>
using Memory = pro::facade_builder
    ::add_convention<get_size, std::size_t() const noexcept>
    ::add_convention<get_data, std::span<T const>() const noexcept>
    ::template add_convention<get_data, std::span<T>() noexcept>
    ::template support_copy<pro::constraint_level::none>
::build;
```

BTW, it is more recommended to define a named `struct` that inherits from `build`. Or otherwise, it may generate a long name for an ABI when `proxy<Memory>` is used on the boundary, which may reduce compilation performance.

**Comment by mingxwa** [comment]
P.S. Because `support_copy` does not depend on `T`, it is generally more recommended to declare `support_xxx` and `restrict_layout` before `add_convention`. There is no need to explicitly declare copyability as `none`, because it is `none` [by default](https://microsoft.github.io/proxy/docs/basic_facade_builder/support_copy.html#notes). Also, the two `get_data` conventions can be merged into one, so that the `template` keyword is no longer needed in your case. The following definition is equivalent to yours:

```cpp
template<typename T = std::byte>
struct Memory : pro::facade_builder
    ::add_convention<get_size, std::size_t() const noexcept>
    ::add_convention<get_data, std::span<T const>() const noexcept, std::span<T>() noexcept>
    ::build {};
```

**Comment by cxxamz** [comment]
Cool, it's working. 
This is a really amazing project. 
Thanks!
