### ISSUE TITLE
can proxy work as a interface for template programming?

### ISSUE THREAD

**Issue by fililili** [microsoft/proxy#184]
Here is an c# [example](https://godbolt.org/z/od1xq7Y81), it can report err clearly. (The T only supports IComparable interface, so when we use operator + in Min function, it reports err)
```csharp
using System;
using System.Numerics;

public class Program
{
    public static T Min<T>(T a, T b) where T : IComparable<T>
     //, IAdditionOperators<T, T, T>
    {
        return a.CompareTo(b) < 0 ? (a + a) : b;
    }

    public static void Main()
    {
        int intA = 10;
        int intB = 20;
        Console.WriteLine("Min of {0} and {1} is {2}", intA, intB, Min(intA, intB));

        double doubleA = 5.5;
        double doubleB = 3.3;
        Console.WriteLine("Min of {0} and {1} is {2}", doubleA, doubleB, Min(doubleA, doubleB));

    }
}
```
In c++, it will **not** throw err. As we all know, the later you find an err, the hard you find the root cause. It makes c++ very hard to debug template function. So, does the usage supports in proxy?

**Comment by mingxwa** [comment]
@fililili It is true that debugging templates in C++ is not as easily as debugging generics in C#, but that's how C++ works: template instantiation only happens when it is used. `proxy` can improve diagnostics when it reduces a function template into a function (e.g., from `Foo(auto arg)` into `Foo(pro::proxy<SomeFacade> arg)`), but `proxy` can't magically make C++ templates easy to debug with.

**Comment by mingxwa** [comment]
@fililili I think the problem here is about diagnostics difference between C# generics and C++ templates, and has nothing to do with "Proxy". In C#, a generic type `T` is **nothing** by default, unless there is a `where`. In C++, a template argument type `T` is **anything** by default, before its instantiation.

> But the IComparable interface cannot just be a proxy because CompareTo needs two same T.

Technically you can, but it is not how C++ template intended to be used, because this mechanism is too weak to help a template library author to write correct code (like me). For example,

```cpp
#include <cstdio>

#include "proxy.h"

template <class T>
struct RestrictedComparable : pro::facade_builder
    ::add_convention<pro::operator_dispatch<"<">, bool(const T& rhs) const>  // Allow operator<
    ::template add_convention<pro::conversion_dispatch<const T&>, const T&() const>  // Allow explicit conversion to const T&
    ::build {};

template <class T>
const T& MyMinImpl(pro::proxy<RestrictedComparable<T>> a, pro::proxy<RestrictedComparable<T>> b) {
  auto& result =  *a < static_cast<const T&>(*b) ? a : b;
  // *a + *a; won't compile
  return static_cast<const T&>(*result);
}

template <class T>
const T& MyMin(const T& a, const T& b) {
  return MyMinImpl<T>(&a, &b);
}

int main() {
  printf("%d\n", MyMin(123, 456));
}
```

Although it works, I don't think it is what you want in production, but let me know if you have any further questions.

**Comment by fililili** [comment]
@mingxwa . Thanks, the code works. But it is a little complicated. In other language like c#/go/rust, they all have interface/trait works for both type erasure (must have) and template function (useful for debug), so I hope c++ can do same thing.
At now I cannot provide more useful question or advise, I will reply if I have other findings later.
