### ISSUE TITLE
Any way to detect narrowing conversion?

### ISSUE THREAD

**Issue by apricot-azumi** [microsoft/proxy#185]
This happened in my embedded MCU project:

```c++
// Facade
PRO_DEF_MEM_DISPATCH(UsbDeviceApp_handleEpStall, handleEpStall);
struct UsbDeviceApp : pro::facade_builder
    ...
    ::add_convention<UsbDeviceApp_handleEpStall, void(uint8_t ep, bool stalled)>
    ::build {};

// Implementation
class UsbJoystickApp {
public:
    ...
    void handleEpStall(bool stalled, uint8_t ep);  // Wrong param order!
};
```

This compiles silently and cost me a day to debug.

As `uint8_t -> bool` is a narrowing conversion, do we have ways to forbid or at least detect them?

This issue is probably conjugate to #142.

**Comment by mingxwa** [comment]
@apricot-azumi Typically, "Proxy" will generate compiler warnings if a narrowing conversion is detected, and the warning level is appropriately configured. However, it appears that the conversion from `uint8_t` to `bool` is not identified as a narrowing conversion, at least in [the latest versions of GCC, Clang, and MSVC at their highest warning levels](https://godbolt.org/z/eWco8rqea). This seems to be a general issue with C++ compilers, rather than something that "Proxy" can address.
