### ISSUE TITLE
Question: Can Facades be composed to allow for construction of more generic facades from more specified ones?

### ISSUE THREAD

**Issue by spectre-ns** [microsoft/proxy#26]
I want to define interfaces in terms of facades using them like requirements for injected classes. I'm wondering if I have a facade that implements a superset of the expected facade can use the bigger interface to construct the more generic one and if so is there a performance hit?

**Comment by mingxwa** [comment]
@spectre-ns 

> I'm wondering if I have a facade that implements a superset of the expected facade can use the bigger interface to construct the more generic one

Yes. You can use `std::tuple` to organize hierarchies of dispatch types (duplications allowed). See [Highlight 4 in the blog post of this library](https://devblogs.microsoft.com/cppblog/proxy-runtime-polymorphism-made-easier-than-ever/#highlight-4-composition-of-abstractions):

```cpp
struct D1;
struct D2;
struct D3;
struct FA : pro::facade<D1, D2, D3> {};
struct FB : pro::facade<D1, std::tuple<D3, D2>> {};
struct FC : pro::facade<std::tuple<D1, D2, D3>, D1, std::tuple<D2, D3>> {};
```

`pro::proxy<FA>`, `pro::proxy<FB>`, `pro::proxy<FC>` are equivalent in terms of functionality and runtime performance.

> if so is there a performance hit?

No. Because flattening a hierarchy of dispatch types happens at compile-time, per the implementation in [proxy.h](https://github.com/microsoft/proxy/blob/main/proxy.h).

Thank you for you comments! Please let us know if you have any further questions or suggestions!

**Comment by spectre-ns** [comment]
I guess I'm not completely following the concept of the tuple in the facade. Is the tuple for FA saying that I have to have D1 in my interface but I can have either D2 or D3?

**Comment by spectre-ns** [comment]
Also if I try to construct a proxy with another proxy does that work?

**Comment by spectre-ns** [comment]
I'm trying to understand 4.2.2 Abstraction of "facade" from the paper. Do you have a working example?

**Comment by mingxwa** [comment]
@spectre-ns 

> Is the tuple for FA saying that I have to have D1 in my interface but I can have either D2 or D3?

No. All `FA`, `FB` and `FC` requires `D1`, `D2` and `D3` to apply. The semantics of `FA`, `FB` and `FC` is similar (but not equivalent) to:

```cpp
struct BaseOfD1 {
  virtual XXX = 0;
  virtual ~BaseOfD1() {}
};
struct BaseOfD2 {
  virtual XXX = 0;
  virtual ~BaseOfD2() {}
};
struct BaseOfD3 {
  virtual XXX = 0;
  virtual ~BaseOfD3() {}
};
struct DerivedOfFA : BaseOfD1, BaseOfD2, BaseOfD3 {};
struct DerivedOfD2AndD3 : BaseOfD2, BaseOfD3 {};
struct DerivedOfFB : BaseOfD1, DerivedOfD2AndD3 {};
struct DerivedOfFC : DerivedOfFA, DerivedOfD2AndD3 {};
```

> Also if I try to construct a proxy with another proxy does that work?

No. Because we found implementing this feature will increase binary size of client code, no matter upcast is actually being used or not, this violates the zero-overhead principle. For example, in the code above, the size of VTABLE of `DerivedOfFC` and `DerivedOfFB` is expected to be larger than `DerivedOfFA`, regardless of the vendor of the compiler, which does not apply to `proxy`. In fact, we found upcasting is important in inheritance-based polymorphism mostly because it is "intrusive". With the non-intrusive approach of `proxy`, we believe the motivation becomes trivial comparing to the impact on performance.

> I'm trying to understand 4.2.2 Abstraction of "facade" from the paper. Do you have a working example?

We do have an example in our tests [proxy_invocation_tests.cpp](https://github.com/microsoft/proxy/blob/bc82582b2a2d7f7c0a87b6e7321eacb61839faff/tests/proxy_invocation_tests.cpp#L119-L132), but maybe we should consider adding a sample for this feature in [samples](https://github.com/microsoft/proxy/tree/main/samples).

**Comment by spectre-ns** [comment]
Thanks, just to summarize. 
1) This library implemented single level inheritance primarily?
2) Upcasting (converting derived to it's base) is actually intrusive and not good design?

I would be interested to hear more about number 2. I would never have guessed that. Closing as you've answered my original question.

**Comment by mingxwa** [comment]
@spectre-ns 

> This library implemented single level inheritance primarily?

That is true from usability perspective. Technically, this `proxy` implemented duck typing rather than inheritance. They represent different paradigms.

> Upcasting (converting derived to it's base) is actually intrusive and not good design?

Yes. This is one of the motivations of this library. As per [Sean Parent's summary](https://www.youtube.com/watch?v=QGcVXgEVMJg): "The requirements of a polymorphic type, by definition, comes from its use, and there are no polymorphic types, only polymorphic use of similar types. Inheritance is the base class of evil." If we use upcasting for abstraction, it is required to define the base types *before* we actually use the types polymorphically. Using `proxy` will escape this limitation.
