### ISSUE TITLE
C++ version support

### ISSUE THREAD

**Issue by lcl1153406** [microsoft/proxy#41]
Can we use it in C++17, and consider supporting C++17？

**Comment by mingxwa** [comment]
The implementation of `proxy` (specifically ctors, dtor, assignments) currently relies on a language feature [Conditionally Trivial Special Member Functions](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0848r3.html) available since C++20. Backporting this code to C++17 is theoretically possible but not trivial.
