### ISSUE TITLE
[FR] Add std::function::target() equivalent

### ISSUE THREAD

**Issue by psiha** [microsoft/proxy#67]
...yet without a separate vtable call entry:
- a void * returning version (the user has to know what is actually inside)
- add a simple boolean to the vtable/meta object: specifying whether the assigned target is in the SBO (and so you return a pointer to the SBO) or on the heap (so you return the pointer stored at the begining of the SBO, I suppose)
(and/or take into consideration https://github.com/microsoft/proxy/issues/66)

**Comment by mingxwa** [comment]
> a void * returning version (the user has to know what is actually inside)

Since most existing polymorphic wrappers in the standard do not support `target()`, there is no plan to add to `proxy`. On the other hand, with the current implementation of `proxy`, it is not trivial to dereference the target without a virtual dispatch.

> add a simple boolean to the vtable/meta object

It can be done with reflection. Please refer to our [unit tests](https://github.com/microsoft/proxy/blob/main/tests/proxy_creation_tests.cpp#L46) as an example (exactly observes SBO).
