### ISSUE TITLE
Undefined behavior: Field `ptr_` of `proxy` is accessed with potentially wrong compile-time assumption

### ISSUE THREAD

**Issue by mingxwa** [microsoft/proxy#80]
As per clause 8 of [basic.life] in the standard:

> If, after the lifetime of an object has ended and before the storage which the object occupied is reused or
released, a new object is created at the storage location which the original object occupied, a pointer that
pointed to the original object, a reference that referred to the original object, or the name of the original
object will automatically refer to the new object and, once the lifetime of the new object has started, can be
used to manipulate the new object, if the original object is transparently replaceable (see below) by the new
object. An object o1 is transparently replaceable by an object o2 if:
> — the storage that o2 occupies exactly overlays the storage that o1 occupied, and
> — **o1 and o2 are of the same type (ignoring the top-level cv-qualifiers)**, and
> — o1 is not a const, complete object, and
> — neither o1 nor o2 is a potentially-overlapping subobject (6.7.2), and
> — either o1 and o2 are both complete objects, or o1 and o2 are direct subobjects of objects p1 and p2,
respectively, and p1 is transparently replaceable by p2.
> [Note 5 : If these conditions are not met, a pointer to the new object can be obtained from a pointer that represents
the address of its storage by calling std::launder (17.6.5). —end note]

There are many places in the implementation of `proxy` that `reinterpret_cast` the data field `alignas(F::constraints.max_align) char ptr_[F::constraints.max_size]` to a user-defined pointer type, which leads to undefined behavior, since `char` and a pointer type `P` may not be `transparently replaceable` as per the wording above.

**Comment by frederick-vs-ja** [comment]
Curiouly, these function don't seem able to be executed during constant evaluation ("compile-time") because of `reinterpret_cast`.

FYI, if [P3006](https://wg21.link/p3006) gets accepted as a DR then we won't need `launder` in these cases. But perhaps we should change the array element type to `unsigned char` because `char[N]` doesn't provide storage (clarified in [CWG2489](https://cplusplus.github.io/CWG/issues/2489.html)).

**Comment by mingxwa** [comment]
@frederick-vs-ja Thanks for the comment!

Regarding `std::launder()` and P3006, I appreciate the heads-up about the DR potentially making `std::launder()` unnecessary in the future. However, for now, keeping the calls to `std::launder()` ensures compatibility with the minimum supported language version (C++20) of `proxy`. Once the library moves to a later standard that incorporates P3006 (if accepted), we can revisit the need for `std::launder()` and potentially remove it to simplify the code.

Regarding char array, you're right, CWG2489 clarifies that the wording around in-place construction with char arrays could be improved. However, using in-place-new on a char array is not UB according to the current standard wording. While the current implementation functions correctly, I agree that switching the element type to `std::byte` improves readability and explicitly clarifies the intent. I have filed #98 to track.

**Comment by frederick-vs-ja** [comment]
> However, using in-place-new on a char array is not UB according to the current standard wording.

It's somehow indirect and curious to tell when and why UB can happen... It's **not** UB to use in-place-new on an array that doesn't provide storage, e.g. placement-newing an object on an `int` array is also itself OK. As per [[intro.object]/3](https://eel.is/c++draft/intro.object#3) and [/4](https://eel.is/c++draft/intro.object#4), the new object isn't nested within the array or the complete object of the array, if any.

As a result, such in-place-new **ends the lifetime of the enclosing complete object and the nested objects that overlap with the newly created object** due to [[basic.life]/1.5](https://eel.is/c++draft/basic.life#1.5). And then any further non-static member function invocation, including destruction, on such an enclosing object (e.g. a `proxy` object) will be UB as per [[basic.life]/6.2](https://eel.is/c++draft/basic.life#6.2) and [/7.2](https://eel.is/c++draft/basic.life#7.2).

**Comment by mingxwa** [comment]
@frederick-vs-ja Thanks for the clarification. Your point about the lifetime of the enclosing object and nested objects is important. While the initial construction seems okay, further member function calls on the enclosing object could become UB if they access the memory used by the in-placed object after its lifetime has ended. To avoid this potential UB and improve code clarity, switching to `std::byte` aligns with the intent of in-place construction and makes the code more explicit.
